_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.7
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
batch_size:
    value: 128
data_type:
    value: real
device:
    value: cpu
dtype:
    value: torch.float64
epoch:
    value: 20
first_ever:
    value: false
latent_dim:
    value: 32
lr:
    value: 0.01
method:
    value: ncdm
name:
    value: ncdm-step1-seed0
seed:
    value: 0
step:
    value: step1
test_size:
    value: 0.2
